#!/usr/bin/env python3
"""Export C test vectors from the Python integer path (offline, floats OK).

Writes generated/test_vectors.h: real backbone head-features (64 px),
head weights/means, expected (sign,exp) outputs from
IntegerPhiHead.int_predict_pixel, and float refs. The C test must match
bit-exactly. Run: python3 gen_vectors.py  (needs baked weights + torch)"""
import numpy as np
from pathlib import Path

HERE = Path(__file__).parent
REPO = HERE.parent
OUT = HERE / 'generated' / 'test_vectors.h'
N = 64


def emit_arr(name, arr, ctype):
    flat = np.asanyarray(arr).reshape(-1)
    lines = [f'const {ctype} {name}[{flat.size}] = {{']
    f = (lambda v: str(int(v))) if 'int' in ctype else (lambda v: repr(float(v)))
    for i in range(0, flat.size, 12):
        lines.append('    ' + ', '.join(f(v) for v in flat[i:i + 12]) + ',')
    lines.append('};')
    return '\n'.join(lines)


def main():
    import sys
    sys.path.insert(0, str(REPO))
    import torch
    from geo_depth import GeometricDepthAnythingV2, preprocess
    from geo_int import IntegerPhiHead

    device = torch.device('cpu')
    geo = GeometricDepthAnythingV2(device=device)
    head = IntegerPhiHead(REPO / 'weights' / 'phi_weights_compact.bin')
    gx, gy = np.meshgrid(np.linspace(0, 1, 518, dtype=np.float32),
                         np.linspace(0, 1, 518, dtype=np.float32))
    rgb = np.stack([gx, gy, np.full((518, 518), 0.5, dtype=np.float32)], axis=-1)
    with torch.no_grad():
        fmaps, ph, pw = geo.backbone.forward_stages(preprocess(rgb))
        fused = geo.neck(fmaps)
        _ = geo.head(fused, ph, pw)
        feat = geo.head.last_features.squeeze(0).permute(1, 2, 0).reshape(-1, 32).numpy()
    sel = np.linspace(0, feat.shape[0] - 1, N).astype(int)
    feat = feat[sel]
    fs, fe = IntegerPhiHead.encode_features(feat)
    exp_s = np.empty(N, dtype=np.int8)
    exp_e = np.empty(N, dtype=np.int32)
    for i in range(N):
        exp_s[i], exp_e[i] = head.int_predict_pixel(fs[i], fe[i])
    ref = head.float_predict(feat)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    parts = ['/* AUTO-GENERATED by gen_vectors.py — real features, 64 px. */',
             f'#define TV_N {N}',
             emit_arr('TV_FS', fs, 'int8_t'),
             emit_arr('TV_FE', fe, 'int32_t'),
             emit_arr('TV_WS', head.w_s, 'int8_t'),
             emit_arr('TV_WE', head.w_e, 'int32_t'),
             emit_arr('TV_MS', head.m_s, 'int8_t'),
             emit_arr('TV_ME', head.m_e, 'int32_t'),
             f'int8_t TV_TMS = {int(head.tm_s)};',
             f'int32_t TV_TME = {int(head.tm_e)};',
             emit_arr('TV_EXP_S', exp_s, 'int8_t'),
             emit_arr('TV_EXP_E', exp_e, 'int32_t'),
             emit_arr('TV_REF', ref, 'double')]
    OUT.write_text('\n\n'.join(parts) + '\n')
    print(f'wrote {OUT}')


if __name__ == '__main__':
    main()
