#!/usr/bin/env python3
"""Offline LUT generator for the C port. Floats live HERE (build machine),
never in phi_int.c. Run: python3 gen_luts.py  (writes generated/luts.h)"""
import math
from pathlib import Path

PHI = (1 + 5 ** 0.5) / 2
LN_PHI = math.log(PHI)
K, BIAS = 512, 32768
OUT = Path(__file__).parent / 'generated' / 'luts.h'


def emit(name, vals, ctype, definition=True):
    if definition:
        lines = [f'const {ctype} {name}[{len(vals)}] = {{']
    else:
        return f'extern const {ctype} {name}[{len(vals)}];'
    for i in range(0, len(vals), 8):
        lines.append('    ' + ', '.join(str(int(v)) for v in vals[i:i + 8]) + ',')
    lines.append('};')
    return '\n'.join(lines)


def main():
    OUT.parent.mkdir(parents=True, exist_ok=True)
    tables = []
    tables.append(('PHI_ADD_LUT', [round(K * math.log(1 + PHI ** (-d / K)) / LN_PHI)
                                   for d in range(4097)], 'int32_t'))
    sub = [0]
    sub += [round(K * math.log(PHI ** (d / K) - 1) / LN_PHI) for d in range(1, 4097)]
    tables.append(('PHI_SUB_LUT', sub, 'int32_t'))
    tables.append(('PHI_FRAC_LUT', [round(PHI ** (-d / K) * 2 ** 18)
                                    for d in range(13313)], 'int32_t'))
    tables.append(('PHI_COARSE_LUT', [round(t * K * math.log(2) / LN_PHI)
                                      for t in range(-64, 129)], 'int32_t'))
    tables.append(('PHI_FINE_LUT', [round(K * math.log((16384 + i) / 16384) / LN_PHI)
                                    for i in range(16384)], 'int32_t'))
    tables.append(('PHI_EXP_LUT', [round(2 ** 24 * math.exp(-d / 2 ** 14))
                                   for d in range(262145)], 'int32_t'))
    gelu = []
    for k in range(2 * 8 * 2 ** 14 + 1):
        x = (k - 8 * 2 ** 14) / 2 ** 14
        gelu.append(round(0.5 * x * (1 + math.erf(x / math.sqrt(2))) * 2 ** 14))
    tables.append(('PHI_GELU_LUT', gelu, 'int32_t'))
    tables.append(('PHI_BASIS_FRAC',
                   [round(PHI ** (i / 512) * 2 ** 40) for i in range(1024)],
                   'int64_t'))
    # NOTE: 40-bit (not 18-bit) basis is REQUIRED, not a luxury: for
    # negative-q bands the two Fibonacci parts are giants that cancel
    # (e.g. +2.2e9 vs -2.2e9 leaving -35). An 18-bit basis rounding
    # (~0.5 ULP x |F|) swamps the residual; 40 bits keeps basis error
    # (~1e-12 relative) far below it. Products need __int128 in C.
    # Fibonacci tables: EXACT Python ints (no floats anywhere here).
    fib = {0: 0, 1: 1}
    for i in range(2, 93):
        fib[i] = fib[i - 1] + fib[i - 2]
    for i in range(-1, -93, -1):
        fib[i] = fib[i + 2] - fib[i + 1]  # F_{n} = F_{n+2} - F_{n+1}
    tables.append(('PHI_FIBTAB', [fib[q] for q in range(-92, 93)], 'int64_t'))
    # LNFIB[q] = round(512*ln(|F_q|)/ln(PHI)), q in [-256,256]; F_0 -> sentinel.
    lnfib = []
    for q in range(-256, 257):
        a, b = 0, 1
        for _ in range(abs(q)):
            a, b = b, a + b
        f = a if q >= 0 else ((-1) ** (abs(q) + 1) * a)
        lnfib.append(-10 ** 9 if f == 0 else round(512 * math.log(abs(f)) / LN_PHI))
    tables.append(('PHI_LNFIB', lnfib, 'int32_t'))
    decls = ['/* AUTO-GENERATED by gen_luts.py — do not edit. Offline floats only. */',
             '#include <stdint.h>']
    defns = ['/* AUTO-GENERATED by gen_luts.py — do not edit. Offline floats only. */',
             '#include "luts.h"']
    for name, vals, ctype in tables:
        decls.append(emit(name, vals, ctype, definition=False))
        defns.append(emit(name, vals, ctype, definition=True))
    OUT.write_text('\n\n'.join(decls) + '\n')
    C_OUT = OUT.parent / 'luts.c'
    C_OUT.write_text('\n\n'.join(defns) + '\n')
    print(f'wrote {OUT} + {C_OUT} ({C_OUT.stat().st_size / 1e6:.2f} MB)')


if __name__ == '__main__':
    main()
