#!/usr/bin/env python3
"""Export bit-exact vectors for the fixed-point/NN C kernels (offline OK).

Writes generated/test_fixed_nn.h. Every expectation comes from the
Python implementation the C file mirrors; the C test must match
EXACTLY (integer ops have no tolerance). Run: python3 gen_fixed_vectors.py
"""
import numpy as np
from pathlib import Path

HERE = Path(__file__).parent
REPO = HERE.parent
OUT = HERE / 'generated' / 'test_fixed_nn.h'


def emit_arr(name, arr, ctype):
    flat = np.asanyarray(arr).reshape(-1)
    lines = [f'const {ctype} {name}[{flat.size}] = {{']
    f = (lambda v: str(int(v))) if 'int' in ctype else (lambda v: repr(float(v)))
    for i in range(0, flat.size, 12):
        lines.append('    ' + ', '.join(f(v) for v in flat[i:i + 12]) + ',')
    lines.append('};')
    return '\n'.join(lines)


def main():
    import sys
    sys.path.insert(0, str(REPO))
    import geo_int as G
    from geo_int import IntegerPhiHead

    rng = np.random.default_rng(11)
    parts = ['/* AUTO-GENERATED by gen_fixed_vectors.py — do not edit. */']

    # 1. fixed_dot: 8 cases x T=48 terms, realistic spread incl. wide gaps
    T, NC = 48, 8
    fds = rng.choice([-1, 1], size=(NC, T)).astype(np.int8)
    fde = (33000 + rng.integers(-6000, 6000, size=(NC, T))).astype(np.int32)
    fde[3] = 33000 + rng.integers(0, 12000, size=T)   # wide-span case
    fde[5] = 20000 + rng.integers(0, 3000, size=T)    # low-band case
    fxs = np.empty(NC, dtype=np.int8)
    fxe = np.empty(NC, dtype=np.int32)
    fxz = np.empty(NC, dtype=bool)
    for i in range(NC):
        # per-dot max scale, exactly as fixed_dot_terms on (T,1) — which is
        # what the C kernel mirrors (one call = one dot = one max).
        s, e, z = G.fixed_dot_terms(fds[i].reshape(T, 1), fde[i].reshape(T, 1))
        fxs[i], fxe[i], fxz[i] = s[0], e[0], z[0]
    parts += [f'#define FD_N {NC}', f'#define FD_T {T}',
              emit_arr('FD_S', fds, 'int8_t'), emit_arr('FD_E', fde, 'int32_t'),
              emit_arr('FD_XS', fxs, 'int8_t'), emit_arr('FD_XE', fxe, 'int32_t'),
              emit_arr('FD_XZ', fxz.astype(np.int8), 'uint8_t')]

    # 2. rescale: q vectors across scales
    rq = (rng.standard_normal((4, 16)) * 2**17).astype(np.int64)
    rm = [33000, 32000, 34000, 31000]
    rstar = [m + d for m, d in zip(rm, (500, 2000, 0, 9000))]
    rout = np.empty_like(rq)
    for i in range(4):
        from geo_int import _to_common_scale
        rout[i] = _to_common_scale(rq[i], rm[i], rstar[i])
    parts += [emit_arr('RS_Q', rq, 'int64_t'),
              emit_arr('RS_M', rm, 'int32_t'),
              emit_arr('RS_MS', rstar, 'int32_t'),
              emit_arr('RS_Y', rout, 'int64_t')]

    # 3. head_fixed: 64px real features -> triple (bit-exact) + float corr
    import torch
    from geo_depth import GeometricDepthAnythingV2, preprocess
    device = torch.device('cpu')
    geo = GeometricDepthAnythingV2(device=device)
    head = IntegerPhiHead(REPO / 'weights' / 'phi_weights_compact.bin')
    gx, gy = np.meshgrid(np.linspace(0, 1, 518, dtype=np.float32),
                         np.linspace(0, 1, 518, dtype=np.float32))
    rgb = np.stack([gx, gy, np.full((518, 518), 0.5, dtype=np.float32)], axis=-1)
    with torch.no_grad():
        fmaps, ph, pw = geo.backbone.forward_stages(preprocess(rgb))
        fused = geo.neck(fmaps)
        _ = geo.head(fused, ph, pw)
        feat = geo.head.last_features.squeeze(0).permute(1, 2, 0).reshape(-1, 32).numpy()
    sel = np.linspace(0, feat.shape[0] - 1, 64).astype(int)
    feat = feat[sel]
    fs, fe = IntegerPhiHead.encode_features(feat)
    hxs = np.empty(64, dtype=np.int8)
    hxe = np.empty(64, dtype=np.int32)
    hxz = np.empty(64, dtype=bool)
    for i in range(64):
        # replicate _head_fixed_pixel's triple via its own steps
        qf, mf = G.to_fixed_group(fs[i], fe[i])
        qm, mm = G.to_fixed_group(head.m_s, head.m_e)
        m = mf if mf >= mm else mm
        qf = G._to_common_scale(qf, mf, m)
        qm = G._to_common_scale(qm, mm, m)
        qc = (qf - qm).astype(np.int64)
        qw, mw = G.to_fixed_group(head.w_s, head.w_e)
        total = sum(int(a) * int(b) for a, b in zip(qc, qw.astype(np.int64)))
        total = (total + (1 << (G.FIXED_F - 1))) >> G.FIXED_F
        s, e, z = G.from_fixed_scalar(total, m + mw - G.BIAS, G.FIXED_F)
        s2, e2 = G.phi_add(s, e, int(head.tm_s), int(head.tm_e),
                           head.add_lut, head.sub_lut)[:2]
        hxs[i], hxe[i], hxz[i] = s2, e2, False
    ref = head.float_predict(feat)
    parts += [emit_arr('HF_FS', fs, 'int8_t'), emit_arr('HF_FE', fe, 'int32_t'),
              emit_arr('HF_WS', head.w_s, 'int8_t'),
              emit_arr('HF_WE', head.w_e, 'int32_t'),
              emit_arr('HF_MS', head.m_s, 'int8_t'),
              emit_arr('HF_ME', head.m_e, 'int32_t'),
              f'int8_t HF_TMS = {int(head.tm_s)};',
              f'int32_t HF_TME = {int(head.tm_e)};',
              emit_arr('HF_XS', hxs, 'int8_t'), emit_arr('HF_XE', hxe, 'int32_t'),
              emit_arr('HF_REF', ref, 'double')]

    # 4. linear: 4x64 -> 32 (logic) + layernorm 4x384 (real width) + gelu 256
    X = (rng.standard_normal((4, 64)) * 2**16).astype(np.int64)
    W = (rng.standard_normal((32, 64)) * 2**10).astype(np.int64)
    b = (rng.standard_normal(32) * 2**12).astype(np.int64)
    Y = G.int_linear_fixed(X, W, b)
    parts += [emit_arr('LN_X', X, 'int64_t'), emit_arr('LN_W', W, 'int64_t'),
              emit_arr('LN_B', b, 'int64_t'), emit_arr('LN_Y', Y, 'int64_t')]
    XN = (rng.standard_normal((4, 384)) * 2**16).astype(np.int64)
    w = (rng.standard_normal(384) * 2**12).astype(np.int64)
    bb = (rng.standard_normal(384) * 2**10).astype(np.int64)
    YN = G.int_layernorm_affine(XN, w, bb)
    parts += [emit_arr('LM_X', XN, 'int64_t'), emit_arr('LM_W', w, 'int64_t'),
              emit_arr('LM_B', bb, 'int64_t'), emit_arr('LM_Y', YN, 'int64_t')]
    XG = np.concatenate([
        np.linspace(-8 * 16384 - 500, 8 * 16384 + 500, 200).astype(np.int64),
        (rng.standard_normal(56) * 30000).astype(np.int64)])
    YG = G.int_gelu_fixed(XG)
    parts += [emit_arr('GE_X', XG, 'int32_t'), emit_arr('GE_Y', YG, 'int64_t')]

    # 5. softmax rows: exact G.int_softmax_fixedvals (varied spreads,
    # wide outlier -> EXP clip path, constant row)
    NS, NN = 6, 24
    SQ = (rng.standard_normal((NS, NN)) * 2**18).astype(np.int64)
    SQ[3] = (rng.standard_normal(NN) * 2**22).astype(np.int64)
    SQ[3, 0] += 1 << 24  # outlier forces clipping on this row
    SQ[4] = 7 * 2**14    # constant row -> uniform
    SNUM, SDEN = G.int_softmax_fixedvals(SQ)
    parts += [f'#define SM_N {NS}', f'#define SM_M {NN}',
              emit_arr('SM_S', SQ, 'int64_t'),
              emit_arr('SM_NUM', SNUM, 'int64_t'),
              emit_arr('SM_DEN', SDEN, 'int64_t')]

    # 6. attention end-to-end: exact G.int_attention_fixed on REAL baked
    # layer0 weights + realistic random tokens (N=8, D=384, heads=6)
    AN, AD, AH = 8, 384, 6
    W = G.bake_layer_fixed(REPO / 'weights' / 'geometric_backbone.npz', 0)
    AX = (rng.standard_normal((AN, AD)) * 2**16).astype(np.int64)
    AO = G.int_attention_fixed(AX, W, heads=AH)
    parts += [f'#define AN_N {AN}', f'#define AN_D {AD}', f'#define AN_H {AH}',
              emit_arr('AN_X', AX, 'int64_t'),
              emit_arr('AN_WQ', W['q.weight'], 'int64_t'),
              emit_arr('AN_WK', W['k.weight'], 'int64_t'),
              emit_arr('AN_WV', W['v.weight'], 'int64_t'),
              emit_arr('AN_WP', W['proj.weight'], 'int64_t'),
              emit_arr('AN_BQ', W['q.bias'], 'int64_t'),
              emit_arr('AN_BK', W['k.bias'], 'int64_t'),
              emit_arr('AN_BV', W['v.bias'], 'int64_t'),
              emit_arr('AN_BP', W['proj.bias'], 'int64_t'),
              emit_arr('AN_O', AO, 'int64_t')]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text('\n\n'.join(parts) + '\n')
    print(f'wrote {OUT}')


if __name__ == '__main__':
    main()
