#!/usr/bin/env python3
"""Offline LUT generator for the C port. Floats live HERE (build machine),
never in phi_int.c. Run: python3 gen_luts.py  (writes generated/luts.h)"""
import math
from pathlib import Path

PHI = (1 + 5 ** 0.5) / 2
LN_PHI = math.log(PHI)
K, BIAS = 512, 32768
OUT = Path(__file__).parent / 'generated' / 'luts.h'


def emit(name, vals, ctype):
    lines = [f'const {ctype} {name}[{len(vals)}] = {{']
    for i in range(0, len(vals), 8):
        lines.append('    ' + ', '.join(str(int(v)) for v in vals[i:i + 8]) + ',')
    lines.append('};')
    return '\n'.join(lines)


def main():
    OUT.parent.mkdir(parents=True, exist_ok=True)
    parts = ['/* AUTO-GENERATED by gen_luts.py — do not edit. Offline floats only. */']
    parts.append(emit('PHI_ADD_LUT', [round(K * math.log(1 + PHI ** (-d / K)) / LN_PHI)
                                      for d in range(4097)], 'int32_t'))
    sub = [0]
    sub += [round(K * math.log(PHI ** (d / K) - 1) / LN_PHI) for d in range(1, 4097)]
    parts.append(emit('PHI_SUB_LUT', sub, 'int32_t'))
    parts.append(emit('PHI_FRAC_LUT', [round(PHI ** (-d / K) * 2 ** 18)
                                       for d in range(13313)], 'int32_t'))
    parts.append(emit('PHI_COARSE_LUT', [round(t * K * math.log(2) / LN_PHI)
                                         for t in range(-64, 129)], 'int32_t'))
    parts.append(emit('PHI_FINE_LUT', [round(K * math.log((16384 + i) / 16384) / LN_PHI)
                                       for i in range(16384)], 'int32_t'))
    parts.append(emit('PHI_EXP_LUT', [round(2 ** 24 * math.exp(-d / 2 ** 14))
                                      for d in range(262145)], 'int32_t'))
    gelu = []
    for k in range(2 * 8 * 2 ** 14 + 1):
        x = (k - 8 * 2 ** 14) / 2 ** 14
        gelu.append(round(0.5 * x * (1 + math.erf(x / math.sqrt(2))) * 2 ** 14))
    parts.append(emit('PHI_GELU_LUT', gelu, 'int32_t'))
    OUT.write_text('\n\n'.join(parts) + '\n')
    print(f'wrote {OUT} ({OUT.stat().st_size / 1e6:.2f} MB)')


if __name__ == '__main__':
    main()
