#!/usr/bin/env python3
"""Emit a shippable C model from a sealed search artifact (scaffold).

The TrialSpec DSL is the intermediate language: artifact JSON in,
C out. Scope is deliberately narrow (version one): the integer head +
exactly the tables its accum path reads, per the honest-bytes rule.
Emission is for SEALED incumbents (pass --artifact); the emitter refuses
unshaped configs.

What it emits into c_port/generated/model_<id8>/:
  model_tables.h  narrowed ADD/SUB (+EXP, shared attention cost) tables
  model_weights.h head (sign,exp) vectors + target mean (from 125B compact)
  model_head.c    size-aware phi_add + head loop (notes the future
                  unification: parameterize phi_int.c by table size
                  instead of this honest duplication)
  model_manifest.json  config, byte counts, provenance

Then compiles model_head.c against the 64px real-feature vectors
(generated/test_vectors.h) and checks bit-exactness vs Python.

Run: python adapt/emit_c.py [--artifact adapt/runs/graduation.json]
"""
import json
import subprocess
import sys
from pathlib import Path

ADAPT = Path(__file__).parent
REPO = ADAPT.parent
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(ADAPT))
sys.path.insert(0, str(ADAPT / 'third_party'))

C_PORT = REPO / 'c_port'
GEN = C_PORT / 'generated'


def load_incumbent(path):
    d = json.load(open(path))
    cfg = d['incumbent']['config']
    if set(cfg) != {"frac_cap", "exp_span", "dmax", "accum"}:
        raise ValueError(f"emitter v1 handles width artifacts only, got {sorted(cfg)}")
    if cfg.get("accum", "tree") != "tree":
        raise ValueError("emitter v1 handles tree accum only (fixed bridge C is future work)")
    return cfg


def build_tables(cfg):
    """Narrowed tables per honest-bytes rule. Offline floats OK (build machine)."""
    import math
    import geo_int as G
    k = G.K
    lnphi = float(G.LN_PHI)
    phi = float(G.PHI)
    dmax = cfg["dmax"]
    add = [round(k * math.log(1 + phi ** (-d / k)) / lnphi) for d in range(dmax + 1)]
    sub = [0] + [round(k * math.log(phi ** (d / k) - 1) / lnphi) for d in range(1, dmax + 1)]
    span = cfg["exp_span"]
    exp = [round(2 ** 24 * math.exp(-d / 2 ** 14)) for d in range(span * (1 << 14) + 1)]
    return {"add": add, "sub": sub, "exp": exp}


def load_head_ints():
    from geo_int import IntegerPhiHead
    head = IntegerPhiHead(REPO / 'weights' / 'phi_weights_compact.bin')
    return head


def emit_array(f, name, vals, ctype):
    f.write(f'static const {ctype} {name}[{len(vals)}] = {{\n')
    for i in range(0, len(vals), 8):
        f.write('    ' + ', '.join(str(int(v)) for v in vals[i:i + 8]) + ',\n')
    f.write('};\n')


def main():
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument('--artifact', default=str(ADAPT / 'runs' / 'graduation.json'))
    args = ap.parse_args()

    cfg = load_incumbent(args.artifact)
    mid8 = __import__('hashlib').sha256(
        json.dumps(cfg, sort_keys=True).encode()).hexdigest()[:8]
    outdir = GEN / f'model_{mid8}'
    outdir.mkdir(parents=True, exist_ok=True)
    print(f"artifact: {cfg} -> {outdir}")

    tables = build_tables(cfg)
    head = load_head_ints()

    with open(outdir / 'model_tables.h', 'w') as f:
        f.write('/* AUTO-GENERATED by adapt/emit_c.py — do not edit. */\n')
        f.write(f'#define MODEL_DMAX {cfg["dmax"]}\n')
        f.write(f'#define MODEL_EXP_N {len(tables["exp"])}\n')
        emit_array(f, 'MODEL_ADD', tables["add"], 'int32_t')
        emit_array(f, 'MODEL_SUB', tables["sub"], 'int32_t')
        emit_array(f, 'MODEL_EXP', tables["exp"], 'int32_t')
    with open(outdir / 'model_weights.h', 'w') as f:
        f.write('/* AUTO-GENERATED by adapt/emit_c.py — do not edit. */\n')
        emit_array(f, 'MODEL_WS', head.w_s.tolist(), 'int8_t')
        emit_array(f, 'MODEL_WE', head.w_e.tolist(), 'int32_t')
        emit_array(f, 'MODEL_MS', head.m_s.tolist(), 'int8_t')
        emit_array(f, 'MODEL_ME', head.m_e.tolist(), 'int32_t')
        f.write(f'static const int8_t MODEL_TMS = {int(head.tm_s)};\n')
        f.write(f'static const int32_t MODEL_TME = {int(head.tm_e)};\n')

    (outdir / 'model_head.c').write_text('''/* AUTO-GENERATED by adapt/emit_c.py — do not edit.
 * Size-aware integer head: same math as phi_int.c/phi_add, duplicated
 * honestly because phi_int.c binds full-size globals. Future work:
 * parameterize phi_int.c by table size and delete this copy. */
#include <stdint.h>
#include "model_tables.h"
#include "model_weights.h"

static void madd(int8_t s1, int32_t e1, int8_t s2, int32_t e2,
                 int8_t *so, int32_t *eo) {
    /* zero is (1,0) by convention */
    int z1 = (s1 == 1 && e1 == 0), z2 = (s2 == 1 && e2 == 0);
    if (z1 && z2) { *so = 1; *eo = 0; return; }
    if (z2) { *so = s1; *eo = e1; return; }
    if (z1) { *so = s2; *eo = e2; return; }
    if (s1 == s2) {
        if (e1 >= e2) {
            int32_t d = e1 - e2;
            *so = s1; *eo = d > MODEL_DMAX ? e1 : e1 + MODEL_ADD[d];
        } else {
            int32_t d = e2 - e1;
            *so = s2; *eo = d > MODEL_DMAX ? e2 : e2 + MODEL_ADD[d];
        }
    } else {
        if (e1 == e2) { *so = 1; *eo = 0; return; }
        if (e1 > e2) {
            int32_t d = e1 - e2;
            *so = s1; *eo = d > MODEL_DMAX ? e1 : e2 + MODEL_SUB[d];
        } else {
            int32_t d = e2 - e1;
            *so = s2; *eo = d > MODEL_DMAX ? e2 : e1 + MODEL_SUB[d];
        }
    }
    if (*eo > 65535) *eo = 65535;
    if (*eo < 0) *eo = 0;
}

void model_head_predict(const int8_t *fs, const int32_t *fe,
                        int8_t *so, int32_t *eo) {
    int8_t acc_s = 1;
    int32_t acc_e = 0;
    int first = 1;
    for (int c = 0; c < 32; c++) {
        int8_t nms = (int8_t)-MODEL_MS[c];
        int8_t cs;
        int32_t ce;
        madd(fs[c], fe[c], nms, MODEL_ME[c], &cs, &ce);
        if (cs == 1 && ce == 0) continue;
        {
            int8_t ps = (int8_t)(cs * MODEL_WS[c]);
            int32_t pe = ce + MODEL_WE[c] - 32768;
            if (pe < 0) pe = 0;
            if (pe > 65535) pe = 65535;
            if (first) { acc_s = ps; acc_e = pe; first = 0; }
            else madd(acc_s, acc_e, ps, pe, &acc_s, &acc_e);
        }
    }
    if (first) { *so = MODEL_TMS; *eo = MODEL_TME; return; }
    madd(acc_s, acc_e, MODEL_TMS, MODEL_TME, so, eo);
}
''')
    manifest = {"config": cfg,
                "tables": {k: len(v) for k, v in tables.items()},
                "table_bytes": sum(len(v) * 4 for v in tables.values()),
                "weights": {"w": 32, "mean": 32, "tm": 1},
                "source_artifact": str(args.artifact)}
    (outdir / 'model_manifest.json').write_text(json.dumps(manifest, indent=1))
    print(f"tables: add={len(tables['add'])} sub={len(tables['sub'])} "
          f"exp={len(tables['exp'])} ({manifest['table_bytes'] / 1024:.0f} kB)")

    # bit-exact check vs Python on the 64px vectors
    test_c = outdir / 'model_test.c'
    test_c.write_text('''/* AUTO-GENERATED by adapt/emit_c.py — do not edit. */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
void model_head_predict(const int8_t *fs, const int32_t *fe,
                        int8_t *so, int32_t *eo);
#include "test_vectors.h"
int main(void) {
    int mism = 0;
    for (int i = 0; i < TV_N; i++) {
        int8_t fs[32], so;
        int32_t fe[32], eo;
        for (int c = 0; c < 32; c++) { fs[c] = TV_FS[i * 32 + c]; fe[c] = TV_FE[i * 32 + c]; }
        model_head_predict(fs, fe, &so, &eo);
        if (so != TV_EXP_S[i] || eo != TV_EXP_E[i]) mism++;
    }
    printf("emitted-model bit-exact mismatches: %d/%d\\n", mism, TV_N);
    if (mism == 0) printf("EMIT: ALL PASS\\n");
    else printf("EMIT: FAIL\\n");
    return mism != 0;
}
''')
    if not (GEN / 'test_vectors.h').exists():
        print("building host test vectors (one-time)...")
        subprocess.run([sys.executable, str(C_PORT / 'gen_vectors.py')], check=True,
                       cwd=str(C_PORT))
    inc = [f'-I{outdir}', f'-I{GEN}']
    exe = outdir / 'model_test'
    subprocess.run(['gcc', '-O2', '-std=c99', '-Wall',
                    str(outdir / 'model_head.c'), str(test_c),
                    '-o', str(exe)] + inc, check=True)
    r = subprocess.run([str(exe)], capture_output=True, text=True)
    print(r.stdout.strip())
    if r.returncode != 0:
        print(r.stderr.strip())
        raise SystemExit(1)
    print(f"emitted {outdir}")


if __name__ == '__main__':
    main()
