#!/usr/bin/env python3
"""Emit a shippable C model from a sealed search artifact.

The TrialSpec DSL is the intermediate language: artifact JSON in,
C out. The emitted model links against the unified core (phi_int.c /
fixed_nn.c) with per-build caps — no duplicated kernels. Two paths:
  tree:  narrowed ADD/SUB/EXP + caps header; test calls phi_head_predict.
  fixed: narrowed ADD/SUB/EXP/FRAC + full COARSE/FINE + caps header;
         test calls phi_head_fixed.

Emission is for SEALED incumbents (pass --artifact). Each path compiles
its test against the 64px real-feature vectors and checks bit-exactness.

Run: python adapt/emit_c.py [--artifact adapt/runs/graduation.json]
"""
import json
import subprocess
import sys
from pathlib import Path

ADAPT = Path(__file__).parent
REPO = ADAPT.parent
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(ADAPT))
sys.path.insert(0, str(ADAPT / 'third_party'))

C_PORT = REPO / 'c_port'
GEN = C_PORT / 'generated'


def load_incumbent(path):
    d = json.load(open(path))
    cfg = d['incumbent']['config']
    if set(cfg) != {"frac_cap", "exp_span", "dmax", "accum"}:
        raise ValueError(f"emitter handles width artifacts only, got {sorted(cfg)}")
    if cfg.get("accum", "tree") not in ("tree", "fixed"):
        raise ValueError(f"emitter handles tree/fixed accum, got {cfg.get('accum')}")
    return cfg


def build_tables(cfg):
    """Narrowed tables per honest-bytes rule. Offline floats OK (build machine)."""
    import math
    import geo_int as G
    k = G.K
    lnphi = float(G.LN_PHI)
    phi = float(G.PHI)
    dmax = cfg["dmax"]
    add = [round(k * math.log(1 + phi ** (-d / k)) / lnphi) for d in range(dmax + 1)]
    sub = [0] + [round(k * math.log(phi ** (d / k) - 1) / lnphi) for d in range(1, dmax + 1)]
    span = cfg["exp_span"]
    exp = [round(2 ** 24 * math.exp(-d / 2 ** 14)) for d in range(span * (1 << 14) + 1)]
    return {"add": add, "sub": sub, "exp": exp}


def build_bridge_tables():
    """Full FRAC/COARSE/FINE via geo_int's own builders (identical values)."""
    import geo_int as G
    frac = G._get_frac()
    coarse, fine = G._get_coarse_fine()
    return {"frac": [int(v) for v in frac], "coarse": [int(v) for v in coarse],
            "fine": [int(v) for v in fine]}


def load_head_ints():
    from geo_int import IntegerPhiHead
    head = IntegerPhiHead(REPO / 'weights' / 'phi_weights_compact.bin')
    return head


def emit_array(f, name, vals, ctype, static=True):
    qual = 'static const ' if static else 'const '
    f.write(f'{qual}{ctype} {name}[{len(vals)}] = {{\n')
    for i in range(0, len(vals), 8):
        f.write('    ' + ', '.join(str(int(v)) for v in vals[i:i + 8]) + ',\n')
    f.write('};\n')


def emit_weights(f, head):
    f.write('/* AUTO-GENERATED by adapt/emit_c.py — do not edit. */\n')
    emit_array(f, 'MODEL_WS', head.w_s.tolist(), 'int8_t')
    emit_array(f, 'MODEL_WE', head.w_e.tolist(), 'int32_t')
    emit_array(f, 'MODEL_MS', head.m_s.tolist(), 'int8_t')
    emit_array(f, 'MODEL_ME', head.m_e.tolist(), 'int32_t')
    f.write(f'static const int8_t MODEL_TMS = {int(head.tm_s)};\n')
    f.write(f'static const int32_t MODEL_TME = {int(head.tm_e)};\n')


def emit_caps(f, cfg):
    f.write('/* AUTO-GENERATED by adapt/emit_c.py — do not edit. */\n')
    f.write(f'#define PHI_DMAX {cfg["dmax"]}\n')
    f.write(f'#define PHI_FRAC_CAP {cfg["frac_cap"]}\n')
    f.write(f'#define PHI_EXP_MAX {cfg["exp_span"] * (1 << 14)}\n')


def emit_phi_tables(f, tables, bridge=None):
    for name, vals in (('PHI_ADD_LUT', tables["add"]),
                       ('PHI_SUB_LUT', tables["sub"]),
                       ('PHI_EXP_LUT', tables["exp"])):
        emit_array(f, name, vals, 'int32_t', static=False)
    if bridge is not None:
        for name, vals in (('PHI_FRAC_LUT', bridge["frac"]),
                           ('PHI_COARSE_LUT', bridge["coarse"]),
                           ('PHI_FINE_LUT', bridge["fine"])):
            emit_array(f, name, vals, 'int32_t', static=False)


def emit_format_tables(f):
    """GELU table via geo_int's own builder (identical values). COARSE/FINE
    travel with bridge (fixed path) or are gc'd away (tree path)."""
    import geo_int as G
    gelu = G._get_gelu_lut()
    emit_array(f, 'PHI_GELU_LUT', [int(v) for v in gelu], 'int32_t', static=False)


def ensure_vectors():
    if not (GEN / 'test_vectors.h').exists():
        print("building host test vectors (one-time)...")
        subprocess.run([sys.executable, str(C_PORT / 'gen_vectors.py')], check=True,
                       cwd=str(C_PORT))


def emit_tree(outdir, cfg, tables, head, args):
    """Narrowed ADD/SUB/EXP + caps; test calls phi_head_predict (unified core)."""
    with open(outdir / 'model_caps.h', 'w') as f:
        emit_caps(f, cfg)
    with open(outdir / 'model_tables.c', 'w') as f:
        f.write('/* AUTO-GENERATED by adapt/emit_c.py — do not edit. */\n')
        f.write('#include <stdint.h>\n')
        emit_phi_tables(f, tables)
        emit_format_tables(f)
    with open(outdir / 'model_weights.h', 'w') as f:
        emit_weights(f, head)
    manifest = {"config": cfg,
                "tables": {k: len(v) for k, v in tables.items()},
                "table_bytes": sum(len(v) * 4 for v in tables.values()),
                "weights": {"w": 32, "mean": 32, "tm": 1},
                "source_artifact": str(args.artifact)}
    (outdir / 'model_manifest.json').write_text(json.dumps(manifest, indent=1))
    print(f"tables: add={len(tables['add'])} sub={len(tables['sub'])} "
          f"exp={len(tables['exp'])} ({manifest['table_bytes'] / 1024:.0f} kB)"
          f" + shared GELU format table (gc'd if uncalled)")
    test_c = outdir / 'model_test.c'
    test_c.write_text('''/* AUTO-GENERATED by adapt/emit_c.py — do not edit. */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include "model_caps.h"
#include "phi_int.h"
#include "test_vectors.h"
int main(void) {
    int mism = 0;
    for (int i = 0; i < TV_N; i++) {
        int8_t fs[32], so;
        int32_t fe[32], eo;
        uint8_t zo = 0, zfz[32];
        for (int c = 0; c < 32; c++) {
            fs[c] = TV_FS[i * 32 + c]; fe[c] = TV_FE[i * 32 + c]; zfz[c] = 0;
        }
        phi_head_predict(fs, fe, zfz, TV_WS, TV_WE, TV_MS, TV_ME,
                         TV_TMS, TV_TME, &so, &eo, &zo);
        if (so != TV_EXP_S[i] || eo != TV_EXP_E[i]) mism++;
    }
    printf("emitted-model bit-exact mismatches: %d/%d\\n", mism, TV_N);
    if (mism == 0) printf("EMIT: ALL PASS\\n");
    else printf("EMIT: FAIL\\n");
    return mism != 0;
}
''')
    ensure_vectors()
    exe = outdir / 'model_test'
    # -ffunction-sections/-Wl,--gc-sections: uncalled kernels (and their
    # tables) are dropped, exactly like a firmware link.
    subprocess.run(['gcc', '-O2', '-std=c99', '-Wall',
                    '-ffunction-sections', '-fdata-sections',
                    '-Wl,--gc-sections',
                    str(C_PORT / 'phi_int.c'),
                    str(outdir / 'model_tables.c'), str(test_c),
                    '-o', str(exe),
                    f'-I{outdir}', f'-I{GEN}', f'-I{C_PORT}'], check=True)
    r = subprocess.run([str(exe)], capture_output=True, text=True)
    print(r.stdout.strip())
    if r.returncode != 0:
        print(r.stderr.strip())
        raise SystemExit(1)


def emit_fixed(outdir, cfg, head, args):
    """Narrowed ADD/SUB/EXP/FRAC + full COARSE/FINE + caps; test calls
    phi_head_fixed (unified core). Narrowed linking is now REAL (caps +
    unsized externs) — no open task remains on this path."""
    import numpy as np
    import geo_int as G
    from geo_int import phi_add
    bridge_full = build_bridge_tables()
    cap = cfg["frac_cap"]
    bridge = {"frac": bridge_full["frac"][:cap + 1],
              "coarse": bridge_full["coarse"], "fine": bridge_full["fine"]}
    tables = build_tables(cfg)
    with open(outdir / 'model_caps.h', 'w') as f:
        emit_caps(f, cfg)
    with open(outdir / 'model_tables.c', 'w') as f:
        f.write('/* AUTO-GENERATED by adapt/emit_c.py — do not edit. */\n')
        f.write('#include <stdint.h>\n')
        emit_phi_tables(f, tables, bridge)
        emit_format_tables(f)
    with open(outdir / 'model_weights.h', 'w') as f:
        emit_weights(f, head)
    # Expected triples computed NOW via geo_int → bit-exact test.
    ensure_vectors()
    import re
    txt = (GEN / 'test_vectors.h').read_text()

    def _get(name, n, dtype):
        m = re.search(name + r'\[.*?\]\s*=\s*\{([^}]*)\}', txt, re.S)
        return np.array([dtype(x) for x in m.group(1).replace(',', ' ').split()[:n]])

    tfs = _get('TV_FS', 64 * 32, np.int8).reshape(64, 32)
    tfe = _get('TV_FE', 64 * 32, np.int32).reshape(64, 32)
    exs = np.empty(64, dtype=np.int8)
    exe = np.empty(64, dtype=np.int32)
    # Expected triples computed under the NARROWED tables (patched globals,
    # same save/restore pattern as graduate.evaluate) so they match the
    # linked C exactly at any widths — not just full.
    from lut_pareto import build_frac_table, build_exp_table
    saved = (G.FRAC_CAP, G._FRAC_LUT, G.DMAX, G._EXP_LUT)
    try:
        G.FRAC_CAP = cfg["frac_cap"]
        G._FRAC_LUT = build_frac_table(cfg["frac_cap"])
        G.DMAX = cfg["dmax"]
        G._EXP_LUT = build_exp_table(cfg["exp_span"])
        add_n = G.build_add_lut(dmax=cfg["dmax"])
        sub_n = G.build_sub_lut(dmax=cfg["dmax"])
        for i in range(64):
            qf, mf = G.to_fixed_group(tfs[i], tfe[i])
            qm, mm = G.to_fixed_group(head.m_s, head.m_e)
            m = mf if mf >= mm else mm
            qf = G._to_common_scale(qf, mf, m)
            qm = G._to_common_scale(qm, mm, m)
            qc = (qf - qm).astype(np.int64)
            qw, mw = G.to_fixed_group(head.w_s, head.w_e)
            total = sum(int(a) * int(b) for a, b in zip(qc, qw.astype(np.int64)))
            total = (total + (1 << (G.FIXED_F - 1))) >> G.FIXED_F
            s, e, z = G.from_fixed_scalar(total, m + mw - G.BIAS, G.FIXED_F)
            s2, e2 = phi_add(s, e, int(head.tm_s), int(head.tm_e),
                             add_n, sub_n)[:2]
            exs[i], exe[i] = s2, e2
    finally:
        G.FRAC_CAP, G._FRAC_LUT, G.DMAX, G._EXP_LUT = saved
    with open(outdir / 'model_expected.h', 'w') as f:
        f.write('/* AUTO-GENERATED by adapt/emit_c.py — do not edit. */\n')
        emit_array(f, 'MODEL_EXP_S', exs.tolist(), 'int8_t')
        emit_array(f, 'MODEL_EXP_E', exe.tolist(), 'int32_t')
    test_c = outdir / 'model_test_fixed.c'
    test_c.write_text('''/* AUTO-GENERATED by adapt/emit_c.py — do not edit. */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include "model_caps.h"
#include "fixed_nn.h"
#include "model_weights.h"
#include "model_expected.h"
#include "test_vectors.h"
int main(void) {
    int mism = 0;
    for (int i = 0; i < TV_N; i++) {
        int8_t fs[32], so;
        int32_t fe[32], eo;
        uint8_t zo;
        for (int c = 0; c < 32; c++) { fs[c] = TV_FS[i * 32 + c]; fe[c] = TV_FE[i * 32 + c]; }
        phi_head_fixed(fs, fe, MODEL_WS, MODEL_WE, MODEL_MS, MODEL_ME,
                       MODEL_TMS, MODEL_TME, &so, &eo, &zo);
        if (so != MODEL_EXP_S[i] || eo != MODEL_EXP_E[i]) mism++;
    }
    printf("fixed-emit bit-exact mismatches: %d/%d\\n", mism, TV_N);
    if (mism == 0) printf("EMIT-FIXED: ALL PASS\\n");
    else printf("EMIT-FIXED: FAIL\\n");
    return mism != 0;
}
''')
    narrowed = {"add": (cfg["dmax"] + 1) * 4, "sub": (cfg["dmax"] + 1) * 4,
                "exp": (cfg["exp_span"] * (1 << 14) + 1) * 4,
                "frac": (cap + 1) * 4, "coarse": 193 * 4, "fine": 16384 * 4}
    manifest = {"config": cfg,
                "tables_narrowed_bytes": narrowed,
                "weights": {"w": 32, "mean": 32, "tm": 1},
                "source_artifact": str(args.artifact)}
    (outdir / 'model_manifest.json').write_text(json.dumps(manifest, indent=1))
    print(f"tables narrowed: {sum(narrowed.values()) / 1024:.0f} kB total")
    exe = outdir / 'model_test_fixed'
    # -ffunction-sections/-Wl,--gc-sections: uncalled kernels (and their
    # tables) are dropped, exactly like a firmware link.
    subprocess.run(['gcc', '-O2', '-std=c99', '-Wall',
                    '-ffunction-sections', '-fdata-sections',
                    '-Wl,--gc-sections',
                    str(C_PORT / 'phi_int.c'), str(C_PORT / 'fixed_nn.c'),
                    str(outdir / 'model_tables.c'), str(test_c),
                    '-o', str(exe),
                    f'-I{outdir}', f'-I{GEN}', f'-I{C_PORT}'], check=True)
    r = subprocess.run([str(exe)], capture_output=True, text=True)
    print(r.stdout.strip())
    if r.returncode != 0:
        print(r.stderr.strip())
        raise SystemExit(1)


def main():
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument('--artifact', default=str(ADAPT / 'runs' / 'graduation.json'))
    args = ap.parse_args()

    cfg = load_incumbent(args.artifact)
    mid8 = __import__('hashlib').sha256(
        json.dumps(cfg, sort_keys=True).encode()).hexdigest()[:8]
    outdir = GEN / f'model_{mid8}'
    outdir.mkdir(parents=True, exist_ok=True)
    print(f"artifact: {cfg} -> {outdir}")

    tables = build_tables(cfg)
    head = load_head_ints()
    if cfg.get("accum", "tree") == "fixed":
        emit_fixed(outdir, cfg, head, args)
    else:
        emit_tree(outdir, cfg, tables, head, args)
    print(f"emitted {outdir}")


if __name__ == '__main__':
    main()
