#!/usr/bin/env python3
"""Emit a shippable C model from a sealed search artifact (scaffold).

The TrialSpec DSL is the intermediate language: artifact JSON in,
C out. Two paths:
  tree:  narrowed ADD/SUB/EXP + self-contained size-aware head loop.
  fixed: full FRAC/COARSE/FINE + ADD/SUB/EXP as PHI_* definitions
         linking in place of luts.c, tested via fixed_nn.c's
         phi_head_fixed. NARROWED fixed linking is pending the
         kernel-parameterization unification; the manifest records
         narrowed byte targets alongside actuals so the gap is explicit.

Emission is for SEALED incumbents (pass --artifact).

What it emits into c_port/generated/model_<id8>/ plus a bit-exact
64px-vector test per path.

Run: python adapt/emit_c.py [--artifact adapt/runs/graduation.json]
"""
import json
import subprocess
import sys
from pathlib import Path

ADAPT = Path(__file__).parent
REPO = ADAPT.parent
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(ADAPT))
sys.path.insert(0, str(ADAPT / 'third_party'))

C_PORT = REPO / 'c_port'
GEN = C_PORT / 'generated'


def load_incumbent(path):
    d = json.load(open(path))
    cfg = d['incumbent']['config']
    if set(cfg) != {"frac_cap", "exp_span", "dmax", "accum"}:
        raise ValueError(f"emitter handles width artifacts only, got {sorted(cfg)}")
    if cfg.get("accum", "tree") not in ("tree", "fixed"):
        raise ValueError(f"emitter handles tree/fixed accum, got {cfg.get('accum')}")
    return cfg


def build_tables(cfg):
    """Narrowed tables per honest-bytes rule. Offline floats OK (build machine)."""
    import math
    import geo_int as G
    k = G.K
    lnphi = float(G.LN_PHI)
    phi = float(G.PHI)
    dmax = cfg["dmax"]
    add = [round(k * math.log(1 + phi ** (-d / k)) / lnphi) for d in range(dmax + 1)]
    sub = [0] + [round(k * math.log(phi ** (d / k) - 1) / lnphi) for d in range(1, dmax + 1)]
    span = cfg["exp_span"]
    exp = [round(2 ** 24 * math.exp(-d / 2 ** 14)) for d in range(span * (1 << 14) + 1)]
    return {"add": add, "sub": sub, "exp": exp}


def build_bridge_tables():
    """Full FRAC/COARSE/FINE via geo_int's own builders (identical values)."""
    import geo_int as G
    frac = G._get_frac()
    coarse, fine = G._get_coarse_fine()
    return {"frac": [int(v) for v in frac], "coarse": [int(v) for v in coarse],
            "fine": [int(v) for v in fine]}


def load_head_ints():
    from geo_int import IntegerPhiHead
    head = IntegerPhiHead(REPO / 'weights' / 'phi_weights_compact.bin')
    return head


def emit_array(f, name, vals, ctype):
    f.write(f'static const {ctype} {name}[{len(vals)}] = {{\n')
    for i in range(0, len(vals), 8):
        f.write('    ' + ', '.join(str(int(v)) for v in vals[i:i + 8]) + ',\n')
    f.write('};\n')


def emit_weights(f, head):
    f.write('/* AUTO-GENERATED by adapt/emit_c.py — do not edit. */\n')
    emit_array(f, 'MODEL_WS', head.w_s.tolist(), 'int8_t')
    emit_array(f, 'MODEL_WE', head.w_e.tolist(), 'int32_t')
    emit_array(f, 'MODEL_MS', head.m_s.tolist(), 'int8_t')
    emit_array(f, 'MODEL_ME', head.m_e.tolist(), 'int32_t')
    f.write(f'static const int8_t MODEL_TMS = {int(head.tm_s)};\n')
    f.write(f'static const int32_t MODEL_TME = {int(head.tm_e)};\n')


def ensure_vectors():
    if not (GEN / 'test_vectors.h').exists():
        print("building host test vectors (one-time)...")
        subprocess.run([sys.executable, str(C_PORT / 'gen_vectors.py')], check=True,
                       cwd=str(C_PORT))


def emit_tree(outdir, cfg, tables, head, args):
    with open(outdir / 'model_tables.h', 'w') as f:
        f.write('/* AUTO-GENERATED by adapt/emit_c.py — do not edit. */\n')
        f.write(f'#define MODEL_DMAX {cfg["dmax"]}\n')
        f.write(f'#define MODEL_EXP_N {len(tables["exp"])}\n')
        emit_array(f, 'MODEL_ADD', tables["add"], 'int32_t')
        emit_array(f, 'MODEL_SUB', tables["sub"], 'int32_t')
        emit_array(f, 'MODEL_EXP', tables["exp"], 'int32_t')
    with open(outdir / 'model_weights.h', 'w') as f:
        emit_weights(f, head)
    (outdir / 'model_head.c').write_text('''/* AUTO-GENERATED by adapt/emit_c.py — do not edit.
 * Size-aware integer head: same math as phi_int.c/phi_add, duplicated
 * honestly because phi_int.c binds full-size globals. Future work:
 * parameterize phi_int.c by table size and delete this copy. */
#include <stdint.h>
#include "model_tables.h"
#include "model_weights.h"

static void madd(int8_t s1, int32_t e1, int8_t s2, int32_t e2,
                 int8_t *so, int32_t *eo) {
    /* zero is (1,0) by convention */
    int z1 = (s1 == 1 && e1 == 0), z2 = (s2 == 1 && e2 == 0);
    if (z1 && z2) { *so = 1; *eo = 0; return; }
    if (z2) { *so = s1; *eo = e1; return; }
    if (z1) { *so = s2; *eo = e2; return; }
    if (s1 == s2) {
        if (e1 >= e2) {
            int32_t d = e1 - e2;
            *so = s1; *eo = d > MODEL_DMAX ? e1 : e1 + MODEL_ADD[d];
        } else {
            int32_t d = e2 - e1;
            *so = s2; *eo = d > MODEL_DMAX ? e2 : e2 + MODEL_ADD[d];
        }
    } else {
        if (e1 == e2) { *so = 1; *eo = 0; return; }
        if (e1 > e2) {
            int32_t d = e1 - e2;
            *so = s1; *eo = d > MODEL_DMAX ? e1 : e2 + MODEL_SUB[d];
        } else {
            int32_t d = e2 - e1;
            *so = s2; *eo = d > MODEL_DMAX ? e2 : e1 + MODEL_SUB[d];
        }
    }
    if (*eo > 65535) *eo = 65535;
    if (*eo < 0) *eo = 0;
}

void model_head_predict(const int8_t *fs, const int32_t *fe,
                        int8_t *so, int32_t *eo) {
    int8_t acc_s = 1;
    int32_t acc_e = 0;
    int first = 1;
    for (int c = 0; c < 32; c++) {
        int8_t nms = (int8_t)-MODEL_MS[c];
        int8_t cs;
        int32_t ce;
        madd(fs[c], fe[c], nms, MODEL_ME[c], &cs, &ce);
        if (cs == 1 && ce == 0) continue;
        {
            int8_t ps = (int8_t)(cs * MODEL_WS[c]);
            int32_t pe = ce + MODEL_WE[c] - 32768;
            if (pe < 0) pe = 0;
            if (pe > 65535) pe = 65535;
            if (first) { acc_s = ps; acc_e = pe; first = 0; }
            else madd(acc_s, acc_e, ps, pe, &acc_s, &acc_e);
        }
    }
    if (first) { *so = MODEL_TMS; *eo = MODEL_TME; return; }
    madd(acc_s, acc_e, MODEL_TMS, MODEL_TME, so, eo);
}
''')
    manifest = {"config": cfg,
                "tables": {k: len(v) for k, v in tables.items()},
                "table_bytes": sum(len(v) * 4 for v in tables.values()),
                "weights": {"w": 32, "mean": 32, "tm": 1},
                "source_artifact": str(args.artifact)}
    (outdir / 'model_manifest.json').write_text(json.dumps(manifest, indent=1))
    print(f"tables: add={len(tables['add'])} sub={len(tables['sub'])} "
          f"exp={len(tables['exp'])} ({manifest['table_bytes'] / 1024:.0f} kB)")
    test_c = outdir / 'model_test.c'
    test_c.write_text('''/* AUTO-GENERATED by adapt/emit_c.py — do not edit. */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
void model_head_predict(const int8_t *fs, const int32_t *fe,
                        int8_t *so, int32_t *eo);
#include "test_vectors.h"
int main(void) {
    int mism = 0;
    for (int i = 0; i < TV_N; i++) {
        int8_t fs[32], so;
        int32_t fe[32], eo;
        for (int c = 0; c < 32; c++) { fs[c] = TV_FS[i * 32 + c]; fe[c] = TV_FE[i * 32 + c]; }
        model_head_predict(fs, fe, &so, &eo);
        if (so != TV_EXP_S[i] || eo != TV_EXP_E[i]) mism++;
    }
    printf("emitted-model bit-exact mismatches: %d/%d\\n", mism, TV_N);
    if (mism == 0) printf("EMIT: ALL PASS\\n");
    else printf("EMIT: FAIL\\n");
    return mism != 0;
}
''')
    ensure_vectors()
    exe = outdir / 'model_test'
    subprocess.run(['gcc', '-O2', '-std=c99', '-Wall',
                    str(outdir / 'model_head.c'), str(test_c),
                    '-o', str(exe),
                    f'-I{outdir}', f'-I{GEN}'], check=True)
    r = subprocess.run([str(exe)], capture_output=True, text=True)
    print(r.stdout.strip())
    if r.returncode != 0:
        print(r.stderr.strip())
        raise SystemExit(1)


def emit_fixed(outdir, cfg, head, args):
    import numpy as np
    import geo_int as G
    from geo_int import phi_add
    bridge = build_bridge_tables()
    # Full-size tables for the link (extern decls in phi_int.h bind full
    # sizes; narrowed tables would OOB until kernels take table sizes —
    # the named open unification task). Narrowed byte counts live in the
    # manifest as targets.
    full = build_tables(dict(cfg, dmax=4096, exp_span=16))
    with open(outdir / 'model_tables.h', 'w') as f:
        f.write('/* AUTO-GENERATED by adapt/emit_c.py — do not edit. */\n')
        f.write(f'#define MODEL_DMAX {cfg["dmax"]}\n')
        f.write(f'#define MODEL_EXP_N {len(full["exp"])}\n')
        emit_array(f, 'MODEL_ADD', full["add"], 'int32_t')
        emit_array(f, 'MODEL_SUB', full["sub"], 'int32_t')
        emit_array(f, 'MODEL_EXP', full["exp"], 'int32_t')
    with open(outdir / 'model_weights.h', 'w') as f:
        emit_weights(f, head)
    with open(outdir / 'model_bridge_tables.c', 'w') as f:
        f.write('/* AUTO-GENERATED by adapt/emit_c.py — do not edit. */\n')
        f.write('#include <stdint.h>\n')
        for name, vals in (('PHI_ADD_LUT', full["add"]),
                           ('PHI_SUB_LUT', full["sub"]),
                           ('PHI_EXP_LUT', full["exp"]),
                           ('PHI_FRAC_LUT', bridge["frac"]),
                           ('PHI_COARSE_LUT', bridge["coarse"]),
                           ('PHI_FINE_LUT', bridge["fine"])):
            f.write(f'const int32_t {name}[{len(vals)}] = {{\n')
            for i in range(0, len(vals), 8):
                f.write('    ' + ', '.join(str(int(v)) for v in vals[i:i + 8]) + ',\n')
            f.write('};\n')
    import math
    gelu = [round(0.5 * (k - 8 * 2**14) / 2**14
                  * (1 + math.erf(((k - 8 * 2**14) / 2**14) / math.sqrt(2))) * 2**14)
            for k in range(2 * 8 * 2**14 + 1)]
    with open(outdir / 'model_bridge_tables.c', 'a') as f:
        f.write(f'const int32_t PHI_GELU_LUT[{len(gelu)}] = {{\n')
        for i in range(0, len(gelu), 8):
            f.write('    ' + ', '.join(str(int(v)) for v in gelu[i:i + 8]) + ',\n')
        f.write('};\n')
    # Expected triples computed NOW via geo_int, so the C test is bit-exact
    # over the emitted-tables link.
    ensure_vectors()
    import re
    txt = (GEN / 'test_vectors.h').read_text()

    def _get(name, n, dtype):
        m = re.search(name + r'\[.*?\]\s*=\s*\{([^}]*)\}', txt, re.S)
        return np.array([dtype(x) for x in m.group(1).replace(',', ' ').split()[:n]])

    tfs = _get('TV_FS', 64 * 32, np.int8).reshape(64, 32)
    tfe = _get('TV_FE', 64 * 32, np.int32).reshape(64, 32)
    exs = np.empty(64, dtype=np.int8)
    exe = np.empty(64, dtype=np.int32)
    for i in range(64):
        qf, mf = G.to_fixed_group(tfs[i], tfe[i])
        qm, mm = G.to_fixed_group(head.m_s, head.m_e)
        m = mf if mf >= mm else mm
        qf = G._to_common_scale(qf, mf, m)
        qm = G._to_common_scale(qm, mm, m)
        qc = (qf - qm).astype(np.int64)
        qw, mw = G.to_fixed_group(head.w_s, head.w_e)
        total = sum(int(a) * int(b) for a, b in zip(qc, qw.astype(np.int64)))
        total = (total + (1 << (G.FIXED_F - 1))) >> G.FIXED_F
        s, e, z = G.from_fixed_scalar(total, m + mw - G.BIAS, G.FIXED_F)
        s2, e2 = phi_add(s, e, int(head.tm_s), int(head.tm_e),
                         head.add_lut, head.sub_lut)[:2]
        exs[i], exe[i] = s2, e2
    with open(outdir / 'model_expected.h', 'w') as f:
        f.write('/* AUTO-GENERATED by adapt/emit_c.py — do not edit. */\n')
        emit_array(f, 'MODEL_EXP_S', exs.tolist(), 'int8_t')
        emit_array(f, 'MODEL_EXP_E', exe.tolist(), 'int32_t')
    test_c = outdir / 'model_test_fixed.c'
    test_c.write_text('''/* AUTO-GENERATED by adapt/emit_c.py — do not edit. */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include "fixed_nn.h"
#include "model_weights.h"
#include "model_expected.h"
#include "test_vectors.h"
int main(void) {
    int mism = 0;
    for (int i = 0; i < TV_N; i++) {
        int8_t fs[32], so;
        int32_t fe[32], eo;
        uint8_t zo;
        for (int c = 0; c < 32; c++) { fs[c] = TV_FS[i * 32 + c]; fe[c] = TV_FE[i * 32 + c]; }
        phi_head_fixed(fs, fe, MODEL_WS, MODEL_WE, MODEL_MS, MODEL_ME,
                       MODEL_TMS, MODEL_TME, &so, &eo, &zo);
        if (so != MODEL_EXP_S[i] || eo != MODEL_EXP_E[i]) mism++;
    }
    printf("fixed-emit bit-exact mismatches: %d/%d\\n", mism, TV_N);
    if (mism == 0) printf("EMIT-FIXED: ALL PASS\\n");
    else printf("EMIT-FIXED: FAIL\\n");
    return mism != 0;
}
''')
    narrowed = {"add": (cfg["dmax"] + 1) * 4, "sub": (cfg["dmax"] + 1) * 4,
                "exp": (cfg["exp_span"] * (1 << 14) + 1) * 4,
                "frac": (cfg["frac_cap"] + 1) * 4, "coarse": 193 * 4,
                "fine": 16384 * 4}
    manifest = {"config": cfg,
                "tables_emitted_full_bytes": {
                    "add": len(full["add"]) * 4, "sub": len(full["sub"]) * 4,
                    "exp": len(full["exp"]) * 4,
                    "frac": len(bridge["frac"]) * 4,
                    "coarse": len(bridge["coarse"]) * 4,
                    "fine": len(bridge["fine"]) * 4},
                "narrowed_targets": narrowed,
                "open": "narrowed linking pending kernel parameterization",
                "weights": {"w": 32, "mean": 32, "tm": 1},
                "source_artifact": str(args.artifact)}
    (outdir / 'model_manifest.json').write_text(json.dumps(manifest, indent=1))
    exe = outdir / 'model_test_fixed'
    subprocess.run(['gcc', '-O2', '-std=c99', '-Wall',
                    str(C_PORT / 'phi_int.c'), str(C_PORT / 'fixed_nn.c'),
                    str(outdir / 'model_bridge_tables.c'), str(test_c),
                    '-o', str(exe),
                    f'-I{outdir}', f'-I{GEN}', f'-I{C_PORT}'], check=True)
    r = subprocess.run([str(exe)], capture_output=True, text=True)
    print(r.stdout.strip())
    if r.returncode != 0:
        print(r.stderr.strip())
        raise SystemExit(1)


def main():
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument('--artifact', default=str(ADAPT / 'runs' / 'graduation.json'))
    args = ap.parse_args()

    cfg = load_incumbent(args.artifact)
    mid8 = __import__('hashlib').sha256(
        json.dumps(cfg, sort_keys=True).encode()).hexdigest()[:8]
    outdir = GEN / f'model_{mid8}'
    outdir.mkdir(parents=True, exist_ok=True)
    print(f"artifact: {cfg} -> {outdir}")

    tables = build_tables(cfg)
    head = load_head_ints()
    if cfg.get("accum", "tree") == "fixed":
        emit_fixed(outdir, cfg, head, args)
    else:
        emit_tree(outdir, cfg, tables, head, args)
    print(f"emitted {outdir}")


def emit_tree(outdir, cfg, tables, head, args):
    with open(outdir / 'model_tables.h', 'w') as f:
        f.write('/* AUTO-GENERATED by adapt/emit_c.py — do not edit. */\n')
        f.write(f'#define MODEL_DMAX {cfg["dmax"]}\n')
        f.write(f'#define MODEL_EXP_N {len(tables["exp"])}\n')
        emit_array(f, 'MODEL_ADD', tables["add"], 'int32_t')
        emit_array(f, 'MODEL_SUB', tables["sub"], 'int32_t')
        emit_array(f, 'MODEL_EXP', tables["exp"], 'int32_t')
    with open(outdir / 'model_weights.h', 'w') as f:
        emit_weights(f, head)
    (outdir / 'model_head.c').write_text('''/* AUTO-GENERATED by adapt/emit_c.py — do not edit.
 * Size-aware integer head: same math as phi_int.c/phi_add, duplicated
 * honestly because phi_int.c binds full-size globals. Future work:
 * parameterize phi_int.c by table size and delete this copy. */
#include <stdint.h>
#include "model_tables.h"
#include "model_weights.h"

static void madd(int8_t s1, int32_t e1, int8_t s2, int32_t e2,
                 int8_t *so, int32_t *eo) {
    /* zero is (1,0) by convention */
    int z1 = (s1 == 1 && e1 == 0), z2 = (s2 == 1 && e2 == 0);
    if (z1 && z2) { *so = 1; *eo = 0; return; }
    if (z2) { *so = s1; *eo = e1; return; }
    if (z1) { *so = s2; *eo = e2; return; }
    if (s1 == s2) {
        if (e1 >= e2) {
            int32_t d = e1 - e2;
            *so = s1; *eo = d > MODEL_DMAX ? e1 : e1 + MODEL_ADD[d];
        } else {
            int32_t d = e2 - e1;
            *so = s2; *eo = d > MODEL_DMAX ? e2 : e2 + MODEL_ADD[d];
        }
    } else {
        if (e1 == e2) { *so = 1; *eo = 0; return; }
        if (e1 > e2) {
            int32_t d = e1 - e2;
            *so = s1; *eo = d > MODEL_DMAX ? e1 : e2 + MODEL_SUB[d];
        } else {
            int32_t d = e2 - e1;
            *so = s2; *eo = d > MODEL_DMAX ? e2 : e1 + MODEL_SUB[d];
        }
    }
    if (*eo > 65535) *eo = 65535;
    if (*eo < 0) *eo = 0;
}

void model_head_predict(const int8_t *fs, const int32_t *fe,
                        int8_t *so, int32_t *eo) {
    int8_t acc_s = 1;
    int32_t acc_e = 0;
    int first = 1;
    for (int c = 0; c < 32; c++) {
        int8_t nms = (int8_t)-MODEL_MS[c];
        int8_t cs;
        int32_t ce;
        madd(fs[c], fe[c], nms, MODEL_ME[c], &cs, &ce);
        if (cs == 1 && ce == 0) continue;
        {
            int8_t ps = (int8_t)(cs * MODEL_WS[c]);
            int32_t pe = ce + MODEL_WE[c] - 32768;
            if (pe < 0) pe = 0;
            if (pe > 65535) pe = 65535;
            if (first) { acc_s = ps; acc_e = pe; first = 0; }
            else madd(acc_s, acc_e, ps, pe, &acc_s, &acc_e);
        }
    }
    if (first) { *so = MODEL_TMS; *eo = MODEL_TME; return; }
    madd(acc_s, acc_e, MODEL_TMS, MODEL_TME, so, eo);
}
''')
    manifest = {"config": cfg,
                "tables": {k: len(v) for k, v in tables.items()},
                "table_bytes": sum(len(v) * 4 for v in tables.values()),
                "weights": {"w": 32, "mean": 32, "tm": 1},
                "source_artifact": str(args.artifact)}
    (outdir / 'model_manifest.json').write_text(json.dumps(manifest, indent=1))
    print(f"tables: add={len(tables['add'])} sub={len(tables['sub'])} "
          f"exp={len(tables['exp'])} ({manifest['table_bytes'] / 1024:.0f} kB)")
    test_c = outdir / 'model_test.c'
    test_c.write_text('''/* AUTO-GENERATED by adapt/emit_c.py — do not edit. */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
void model_head_predict(const int8_t *fs, const int32_t *fe,
                        int8_t *so, int32_t *eo);
#include "test_vectors.h"
int main(void) {
    int mism = 0;
    for (int i = 0; i < TV_N; i++) {
        int8_t fs[32], so;
        int32_t fe[32], eo;
        for (int c = 0; c < 32; c++) { fs[c] = TV_FS[i * 32 + c]; fe[c] = TV_FE[i * 32 + c]; }
        model_head_predict(fs, fe, &so, &eo);
        if (so != TV_EXP_S[i] || eo != TV_EXP_E[i]) mism++;
    }
    printf("emitted-model bit-exact mismatches: %d/%d\\n", mism, TV_N);
    if (mism == 0) printf("EMIT: ALL PASS\\n");
    else printf("EMIT: FAIL\\n");
    return mism != 0;
}
''')
    ensure_vectors()
    exe = outdir / 'model_test'
    subprocess.run(['gcc', '-O2', '-std=c99', '-Wall',
                    str(outdir / 'model_head.c'), str(test_c),
                    '-o', str(exe),
                    f'-I{outdir}', f'-I{GEN}'], check=True)
    r = subprocess.run([str(exe)], capture_output=True, text=True)
    print(r.stdout.strip())
    if r.returncode != 0:
        print(r.stderr.strip())
        raise SystemExit(1)


if __name__ == '__main__':
    main()
